services:
  jupyter:
    build:
      context: .
      dockerfile: ./resources/jupyter.Dockerfile
      args:
        NB_UID: ${UID}
        NB_GID: ${GID}
    container_name: ai_jobs_python_jupyter_${UID}
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ../data:/app/data
      - ./src:/app/main
    env_file: .env
    group_add:
      - users
    working_dir: /app/main
    #shm_size: 40G
    command: jupyter lab --no-browser --ip=0.0.0.0 --port ${JUPYTER_PORT}

  ai_jobs_scraper:
    # remove after execution

    build:
      context: .
      dockerfile: ./resources/python.Dockerfile
      target: python
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: ai_job_python_scrape_${UID}
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./:/app/main
    env_file: .env
    group_add:
      - users
    working_dir: /app/main/
    shm_size: 40G
    command: python3 /app/main/ai_jobs_scraper.py
